Repository mahendrapaipuri/grafana-dashboard-reporter-app, pull requests merged in 2024-07, with the labels that each got.

#50 deps: Update all backend dependencies
  .github/workflows/ci.yml
  .github/workflows/is-compatible.yml
  .github/workflows/release.yml
  go.mod
  go.sum
Labels: ci

#53 feat: inline images in report html
  pkg/plugin/report.go
  pkg/plugin/report_test.go
  pkg/plugin/templates/report.gohtml
Labels: enhancement

#58 Remove vfs dependency entirely
  go.mod
  go.sum
  pkg/plugin/app.go
  pkg/plugin/client.go
  pkg/plugin/client_test.go
  pkg/plugin/dashboard.go
  pkg/plugin/report.go
  pkg/plugin/report_test.go
  pkg/plugin/resources.go
  pkg/plugin/templates/footer.gohtml
  pkg/plugin/templates/report.gohtml
  provisioning/plugins/app.yaml
  src/README.md
  src/components/AppConfig/AppConfig.tsx
  src/components/testIds.ts
Labels: maintenance

#55 Split config into sections
  docker-compose.yaml
  package.json
  src/README.md
  src/components/AppConfig/AppConfig.tsx
  src/img/dark.png
  src/img/light.png
  tests/appConfig.spec.ts
  yarn.lock
Labels: enhancement
